# Generated by Django 4.2.3 on 2024-02-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estacionamento", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placa", models.CharField(max_length=20, unique=True)),
                ("modelo", models.CharField(max_length=100)),
                ("cor", models.CharField(max_length=50)),
            ],
        ),
    ]
