# Generated by Django 4.2.3 on 2024-02-14 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("estacionamento", "0002_carro"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_entrada", models.DateTimeField()),
                ("data_saida", models.DateTimeField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "carro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estacionamento.carro",
                    ),
                ),
                (
                    "vaga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estacionamento.vaga",
                    ),
                ),
            ],
        ),
    ]
