# Generated by Django 4.2.3 on 2024-02-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estacionamento", "0003_reserva"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="data_saida",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="valor",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
